In [14]:
import pandas as pd

In [15]:
df = pd.read_csv("/content/drive/MyDrive/SM_SIR/Dataset/weather_forecast.csv");
df

Outlook Temperature Humidity   Windy Play
0      Sunny         Hot     High    Weak   No
1      Sunny         Hot     High  Strong   No
2   Overcast         Hot     High    Weak  Yes
3       Rain        Mild     High    Weak  Yes
4       Rain        Cool   Normal    Weak  Yes
5       Rain        Cool   Normal  Strong   No
6   Overcast        Cool   Normal  Strong  Yes
7      Sunny        Mild     High    Weak   No
8      Sunny        Cool   Normal    Weak  Yes
9       Rain        Mild   Normal    Weak  Yes
10     Sunny        Mild   Normal  Strong  Yes
11  Overcast        Mild     High  Strong  Yes
12  Overcast         Hot   Normal    Weak  Yes
13      Rain        Mild     High  Strong   No

In [6]:
Outlook = ['Sunny', 'Sunny', 'Overcast', 'Rain', 'Rain', 'Rain', 'Overcast', 'Sunny', 'Sunny', 'Rain', 'Sunny', 'Overcast', 'Overcast', 'Rain']
Temp = ['Hot', 'Hot', 'Hot', 'Mild', 'Cool', 'Cool', 'Cool', 'Mild', 'Cool', 'Mild', 'Mild', 'Mild', 'Hot', 'Mild']
Humidity = ['High', 'High', 'High', 'High', 'Normal', 'Normal', 'Normal', 'High', 'Normal', 'Normal', 'Normal', 'High', 'Normal', 'High']
Windy = ['Weak', 'Strong', 'Weak', 'Weak', 'Weak', 'Strong', 'Strong', 'Weak', 'Weak', 'Weak', 'Strong', 'Strong', 'Weak', 'Strong']
Play = ['No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No']


res = []
for column in df.columns:
  li = df[column].tolist()
  res.append(li)
print(res)

[['Sunny', 'Sunny', 'Overcast', 'Rain', 'Rain', 'Rain', 'Overcast', 'Sunny', 'Sunny', 'Rain', 'Sunny', 'Overcast', 'Overcast', 'Rain'], ['Hot', 'Hot', 'Hot', 'Mild', 'Cool', 'Cool', 'Cool', 'Mild', 'Cool', 'Mild', 'Mild', 'Mild', 'Hot', 'Mild'], ['High', 'High', 'High', 'High', 'Normal', 'Normal', 'Normal', 'High', 'Normal', 'Normal', 'Normal', 'High', 'Normal', 'High'], ['Weak', 'Strong', 'Weak', 'Weak', 'Weak', 'Strong', 'Strong', 'Weak', 'Weak', 'Weak', 'Strong', 'Strong', 'Weak', 'Strong'], ['No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No']]


In [16]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
Outlook_encoded = le.fit_transform(Outlook)
Temp_encoded = le.fit_transform(Temp)
Humid_encoded = le.fit_transform(Humidity)
Windy_encoded = le.fit_transform(Windy)
Play_encoded = le.fit_transform(Play)
print(Outlook_encoded)
print(Temp_encoded)
print(Humid_encoded)
print(Windy_encoded)
print(Play_encoded)

#(2: Sunny,1: Overcast,0: Rain) --> Outlook
#(1:Hot,2:Mild,0:Cool)-->Temp
#(0:High,1:Normal)--> Humid
#(1:Weak,0:Strong) --> Wind
#(1:Yes,0: No)-->Play

[2 2 0 1 1 1 0 2 2 1 2 0 0 1]
[1 1 1 2 0 0 0 2 0 2 2 2 1 2]
[0 0 0 0 1 1 1 0 1 1 1 0 1 0]
[1 0 1 1 1 0 0 1 1 1 0 0 1 0]
[0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [12]:
import numpy as np
zipped = zip(Outlook_encoded,Temp_encoded,Humid_encoded,Windy_encoded)
features = np.array(list(zipped)).tolist()
print(features)

[[2, 1, 0, 1], [2, 1, 0, 0], [0, 1, 0, 1], [1, 2, 0, 1], [1, 0, 1, 1], [1, 0, 1, 0], [0, 0, 1, 0], [2, 2, 0, 1], [2, 0, 1, 1], [1, 2, 1, 1], [2, 2, 1, 0], [0, 2, 0, 0], [0, 1, 1, 1], [1, 2, 0, 0]]


In [17]:
from sklearn.naive_bayes import CategoricalNB

model = CategoricalNB()

model.fit(features,Play)

output = model.predict([[2,0,1,1]])# 2: Sunny,0: Cool,1:Normal,1: Weak
print("Predicted Output: ",output)

Predicted Output:  ['Yes']
